security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        MyProject\UserBundle\Entity\User: sha512
    providers:
#        in_memory:
#            memory: ~
        default_provider:
            memory:
                users:
                    admin: { password: admin, roles: 'ROLE_ADMIN' }

    firewalls:
        secured_area:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path: audsur_security_login
                check_path: audsur_security_login_check
                default_target_path: admin_index

    access_control:
        - { path: /admin/, roles: ROLE_ADMIN }