audsur_shop_get_products:
    path:     /
    defaults: {_controller: AudsurShopBundle:Default:getProducts}

audsur_shop_get_products_index:
    path:     /alle/{paginatorIndex}
    defaults: {_controller: AudsurShopBundle:Default:getProducts}

audsur_shop_get_single_product:
    path:     /{productSlug}
    defaults: {_controller: AudsurShopBundle:Default:getSingleProduct}

audsur_shop_get_category:
    path:     /categorie/{slug}
    defaults: {_controller: AudsurShopBundle:Default:getGroup, type: Category}

audsur_shop_get_brand:
    path:     /merk/{slug}
    defaults: {_controller: AudsurShopBundle:Default:getGroup, type: Brand}

